name: Create Draft Release

on:
  workflow_dispatch:
    inputs:
      VERSION_NUMBER:
        type: string
        description: 'the version number to set (x.y.z)'
        required: yes

jobs:
  prepare-release:
    uses: vwdfive/acpp-actions/.github/workflows/fe-prepare-release.yml@v4
    with:
      version_number: ${{ inputs.VERSION_NUMBER }}
    secrets: inherit
          
